SIM_DIASCA_TOP = ../..


.PHONY: all

OVERALL_DOCUMENT_SOURCE = $(TECH_MANUAL)


# Default do-nothing target:
all:
	@echo "  Run 'make full-doc' to generate the technical "\
	"manual ($(TECH_MANUAL))."


DOCUTILS_TOP = $(SIM_DIASCA_TOP)


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
