SIM_DIASCA_TOP = ../..


.PHONY: all full-doc-local clean-local


OVERALL_DOCUMENT_SOURCE = $(COUPLING_HOWTO)

# Default do-nothing target:
all:
	@echo "  Run 'make full-doc' to generate the "\
	"coupling HOWTO ($(COUPLING_HOWTO))."


# Root specified as we want to catch the doc in src/core as well:
#
DOCUTILS_TOP = $(SIM_DIASCA_TOP)


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
