SIM_DIASCA_TOP = ../../..


MODULES_DIRS = bindings case-support dataflow data-management deployment       \
			   instance-creation plugins random resilience scheduling


include $(SIM_DIASCA_TOP)/GNUmakesettings.inc
